<?php
/**
 * Payment Wallee Terminal Method
 *
 * @author: appsbd
 * @package VitePos_Lite\Libs
 */

namespace VitePos_Lite\Libs;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class Payment_Wallee_Terminal_Method
 *
 * @package VitePos_Lite\Libs
 */
class Payment_Wallee_Terminal_Method extends Payment_Method_Base {

	/**
	 * The initialize is generated by appsbd
	 */
	public function initialize() {
		$this->set_admin_name( 'wallee_terminal' );
		$this->title              = 'Wallee Terminal';
		$this->id                 = 'W';
		$this->comp               = 'basic';
		$this->admin_data->is_pro = 'Y';
		$this->set_next_handler( 'STP', 'WalleeTerminal' );
	}

	/**
	 * The set admin settings is generated by appsbd
	 */
	public function set_admin_settings() {
		$this->set_admin_title_desc(
			'Enable %{brand} Payment',
			'It will allow you to take payment using %{brand} Payment gateway, make sure you have added %{brand} api info in %{brand} settings tab.',
			array( 'brand' => 'Wallee Terminal' )
		);
	}
}
