<?php
/**
 * Payment Woocommerce Payment Method
 *
 * @author: appsbd
 * @package VitePos_Lite\Libs
 */

namespace VitePos_Lite\Libs;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class Payment_Woo_Methods
 *
 * @package VitePos_Lite\Libs
 */
class Payment_Woo_Methods extends Payment_Method_Base {
	/**
	 * The initialize is generated by appsbd
	 */
	public function initialize() {
		$this->set_admin_name( 'woocommerce' );
		$this->title              = 'WC Payment';
		$this->id                 = 'B';
		$this->comp               = 'basic';
		$this->admin_data->is_pro = 'Y';
		$this->set_next_handler( 'IFR', 'iframeModal' );
	}

	/**
	 * The is enable is generated by appsbd
	 *
	 * @return false
	 */
	public function is_enable() {
		return false;
	}

	/**
	 * The set admin settings is generated by appsbd
	 */
	public function set_admin_settings() {
		$this->set_admin_title_desc(
			'Enable %{brand} Payment',
			'It will allows to take payment using %{brand} payment methods.',
			array( 'brand' => 'Woocommerce' )
		);
	}
}
