<?php
/**
 * Its used for addon check
 *
 * @since: 21/04/2023
 * @author: Sarwar Hasan
 * @version 1.0.0
 * @package VitePos\Libs
 */

namespace VitePos_Lite\Libs;

use Appsbd_Lite\V5\libs\App_Process;
use Appsbd_Lite\V5\libs\Appsbd_Addon;
use SimplePie\Exception;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}


if ( ! class_exists( __NAMESPACE__ . '\Vitepos_Addons' ) ) {
	/**
	 * Class Vitepos_Loader
	 *
	 * @package VitePos\Libs
	 */
	class Vitepos_Addons {
		/**
		 * Its property result
		 *
		 * @var bool
		 */
		protected $result = false;
		/**
		 * Its property pid
		 *
		 * @var int
		 */
		private $pid = 11;
		/**
		 * Its property plugin_file
		 *
		 * @var string
		 */
		public string $plugin_file;
		/**
		 * Its property loader
		 *
		 * @var Vitepos_Loader
		 */
		protected Vitepos_Loader $loader;

		/**
		 * Vitepos_Addons constructor.
		 *
		 * @param bool           $result Its restuls.
		 * @param string         $base_file Its plugin base file.
		 * @param Vitepos_Loader $loader Its loader object.
		 */
		public function __construct( $result, $base_file, &$loader ) {
			$this->result      = $result;
			$this->plugin_file = $base_file;
			$this->loader      =&$loader;
			add_action( 'init', array( $this, 'addons' ), 999 );
			add_action( 'vitepos/action/check-addon-list', array( $this, 'check_new_addons' ) );
			add_action( 'vitepos/action/check-addon-pre', array( $this, 'check_addons' ) );
			add_filter( 'vitepos/filter/addons-list', array( $this, 'saved_addon_list' ) );
			add_filter(
				'cron_schedules',
				function ( $schedules ) {
					$schedules['vt_weekly'] = array(
						'interval' => 604800,
						'display'  => __( 'Once Weekly', 'vitepos-lite' ),
					);
					return $schedules;
				}
			);
			register_activation_hook(
				$base_file,
				function () {
					if ( ! wp_next_scheduled( 'vitepos/action/check-addon-list' ) ) {
						wp_schedule_event( time(), 'vt_weekly', 'vitepos/action/check-addon-list' );
					}}
			);
			register_deactivation_hook(
				$base_file,
				function () {
					wp_clear_scheduled_hook( 'vitepos/action/check-addon-list' );
				}
			);
			add_filter(
				'wp_signature_hosts',
				function ( $hosts ) {
					$hosts[] = 'appsbd.com';
					$hosts[] = 'addon.appsbd.com';
					$hosts[] = 'localhost';
					return $hosts;
				}
			);
			require_once dirname( $this->plugin_file ) . '/dci/start.php';
			add_action( 'admin_init', array( $this, 'dci_plugin_vitepos_lite' ) );
			add_action( 'admin_enqueue_scripts', array( $this, 'dci_enqueue_scripts' ) );
		}

		/**
		 * The dci enqueue scripts is generated by appsbd
		 */
		public function dci_enqueue_scripts() {
			wp_enqueue_script( 'apbd-dci-sdk', plugins_url( 'dci/assets/js/dci.js', $this->plugin_file ), array( 'jquery' ), $this->loader->plugin_version, true );
			wp_register_style( 'apbd-dci-sdk-vitepos_lite', plugins_url( 'dci/assets/css/dci.css', $this->plugin_file ), array(), $this->loader->plugin_version, 'all' );
			wp_enqueue_style( 'apbd-dci-sdk-vitepos_lite' );
		}
		/**
		 * The dci plugin vitepos lite is generated by appsbd
		 */
		public function dci_plugin_vitepos_lite() {
			$custom_data = array(
				'pos_mode'    => '',
				'pos_link'    => '',
				'pos_version' => $this->loader->plugin_version,
			);
			if ( class_exists( '\VitePos_Lite\Modules\POS_Settings' ) && \VitePos_Lite\Modules\POS_Settings::get_module_instance() ) {
				$custom_data = array(
					'pos_mode'    => \VitePos_Lite\Modules\POS_Settings::get_pos_mode(),
					'pos_link'    => \VitePos_Lite\Modules\POS_Settings::get_module_instance()->get_pos_link(),
					'pos_version' => $this->loader->plugin_version,
				);
			} elseif ( class_exists( '\VitePos\Modules\POS_Settings' ) && \VitePos\Modules\POS_Settings::get_module_instance() ) {

				$custom_data = array(
					'pos_mode'    => \VitePos\Modules\POS_Settings::get_pos_mode(),
					'pos_link'    => \VitePos\Modules\POS_Settings::get_module_instance()->get_pos_link(),
					'pos_version' => $this->loader->plugin_version,
				);
			}
			$data_skip = false;
			if ( function_exists( 'appsbd_is_activated_plugin' ) && appsbd_is_activated_plugin( 'vitepos/vitepos.php' ) ) {
				$data_skip = true;
			}

			vitepos_dci_dynamic_init(
				array(
					'sdk_version'          => '1.2.1',
					'product_id'           => 1,
					'plugin_name'          => 'Vitepos',
					'data_skip'            => $data_skip,
					'version'              => $this->loader->plugin_version,

					'plugin_title'         => 'Vitepos',

					'plugin_icon'          => plugins_url( '/assets/logo.svg', __FILE__ ),

					'api_endpoint'         => 'https://analytics.appsbd.com/wp-json/dci/v1/data-insights',
					'slug'                 => 'vitepos-lite',

					'core_file'            => false,
					'plugin_deactivate_id' => 'vitepos-lite',
					'menu'                 => array(
						'slug' => 'vitepos-lite',
					),
					'public_key'           => 'pk_NvdzlOBFb70bR19RRSNnHZ0Hv32YtrsU',
					'key_prefix'           => 'vitepos',

					'is_premium'           => false,
					'custom_data'          => $custom_data,
					'popup_notice'         => false,
					'deactivate_feedback'  => true,
					'delay_time'           => array(
						'time' => 3 * DAY_IN_SECONDS,
					),
					'text_domain'          => 'vitepos-lite',
					'plugin_msg'           => __(
						'Please help us by contributing anonymous usage data to improve our product, without collecting any sensitive information.',
						'vitepos-lite'
					),
				)
			);
		}

		/**
		 * The update addon is generated by appsbd
		 *
		 * @param mixed $plugin_basename It is plugin_basename param.
		 * @param mixed $download_url It is download_url param.
		 *
		 * @return true|WP_Error|void
		 */
		public function update_addon( $plugin_basename, $download_url ) {
			try {
				return App_Process::app_in( $plugin_basename, $download_url );
			} catch ( \Exception $e ) {
				return false;
			}
		}


		/**
		 * The addons is generated by appsbd
		 */
		public function addons() {

			$last_check = get_option( '_vt_ac', '' );
			if ( empty( $last_check ) ) {
				update_option( '_vt_ac', strtotime( '+5 Days' ) );
			} elseif ( time() < $last_check ) {
				if ( strtotime( '+15 Days' ) < $last_check ) {
					update_option( '_vt_ac', strtotime( '+5 Days' ) );
				} else {
					$this->check_updates();
					return;
				}
			}
			/**
			 * Its for check is there any change before process
			 *
			 * @since 2.0
			 */
			do_action( 'vitepos/action/check-addon-list' );

			update_option( '_vt_ac', strtotime( '+5 Days' ) );
			$this->check_updates();
		}

		/**
		 * The check updates is generated by appsbd
		 */
		public function check_updates() {
			$updates = get_option( 'apps_bd_ups', array() );
			foreach ( $updates as $base_name => $link ) {
				if ( @$this->update_addon( $base_name, $link ) ) {
					unset( $updates[ $base_name ] );
				}
			}
			update_option( 'apps_bd_ups', $updates );
		}

		/**
		 * The addon list is generated by appsbd
		 *
		 * @return mixed
		 */
		public function addon_list() {
			return Appsbd_Addon::addon_list( $this->pid, 'vt', $this->result );
		}

		/**
		 * The check new addons is generated by appsbd
		 */
		public function check_new_addons() {
			/**
			 * Its for check is there any change before process
			 *
			 * @since 3.0.4
			 */
			do_action( 'vitepos/action/check-addon-pre' );
			$this->addon_list();
		}

		/**
		 * The check addons is generated by appsbd
		 */
		public function check_addons() {
			$old_addon = get_option( 'vt_addons', array() );
			if ( ! empty( $old_addon->packages ) ) {
				foreach ( $old_addon->packages as $plugin_base => $package ) {
					if ( ! empty( $package ) && ! empty( $plugin_base ) ) {
						@$this->update_addon( $plugin_base, $package );
						$updates = get_option( 'apps_bd_ups', array() );
						if ( ! empty( $updates[ $plugin_base ] ) ) {
							unset( $updates[ $plugin_base ] );
							update_option( 'apps_bd_ups', $updates );
						}
					}
				}
				unset( $old_addon->packages );
				update_option( 'vt_addons', $old_addon );
			}
		}
		/**
		 * The clean bearer is generated by appsbd
		 *
		 * @param mixed $b It is b param.
		 */
		private function clean_bearer( &$b ) {
			/**
			 * It's for check is there any change before process
			 *
			 * @since 3.0
			 */
			$b = vitepos_apply_filters( 'appsbd/filter/clean-bearer', $b, 'apbdaddonenc_' . $this->pid );
		}

		/**
		 * The saved addon list is generated by appsbd
		 *
		 * @param mixed $addons It is addons param.
		 *
		 * @return array|false|mixed
		 */
		public function saved_addon_list( $addons = array() ) {
			$addons = get_option( 'vt_addons', null );
			if ( empty( $addons ) ) {
				$addons = $this->addon_list();
			}
			if ( ! empty( $addons->addons ) ) {
				return $addons->addons;
			}
			return array();
		}
	}
}
