<?php
/**
 * Its for EPOS settings module
 *
 * @package VitePos\Modules
 */

namespace VitePos_Lite\Modules;

use Appsbd_Lite\V5\libs\Ajax_Confirm_Response;
use Appsbd_Lite\V5\libs\Ajax_Data_Response;
use Appsbd_Lite\V5\libs\Ajax_Response;
use Appsbd_Lite\V5\libs\AppInput;
use Automattic\WooCommerce\Blueprint\Steps\ActivatePlugin;
use VitePos_Lite\Core\Vitepos_Module;


/**
 * Class APBD_EPOS_Settings
 */
class MU_Plugin_Settings extends Vitepos_Module {

	/**
	 * The initialize is generated by appsbd
	 */
	public function initialize() {
	}

	/**
	 * The on init is generated by appsbd
	 */
	public function on_init() {
		parent::on_init();
		$this->add_ajax_action( 'skip-plugin', array( $this, 'action_skip_plugin' ) );
	}

	/**
	 * The get mu pre activate is generated by appsbd
	 *
	 * @return string
	 */
	public static function get_mu_pre_activate() {
		return 'OK I am from';
	}

	/**
	 * The action skip plugin is generated by appsbd
	 */
	public function action_skip_plugin() {
		$plugin        = AppInput::post_value( 'plugin' );
		$target_status = AppInput::post_value( 'status' );
		$res           = new Ajax_Confirm_Response();
		if ( ! empty( $plugin ) ) {
			if ( is_plugin_active( $plugin ) ) {
				$mu_skipped = get_option( '_vt_mu_skipped', array() );
				if ( 'Y' == $target_status ) {
					if ( ! in_array( $plugin, $mu_skipped ) ) {
						$mu_skipped[] = $plugin;
					} else {
						$res->add_info( 'Success ' );

						$res->display_with_response( true, $target_status );
					}
				} elseif ( in_array( $plugin, $mu_skipped ) ) {
					$key = array_search( $plugin, $mu_skipped );
					if ( false !== $key ) {
						unset( $mu_skipped[ $key ] );
						$mu_skipped = array_values( $mu_skipped );
					}
				}

				if ( update_option( '_vt_mu_skipped', $mu_skipped ) ) {
					$res->add_info( 'Successfully Updated' );

					 $res->display_with_response( true, $target_status );
				} else {
					$res->add_error( 'Process failed' );

					 $res->display_with_response( false );
				}
			} else {
				$res->add_error( 'Inactivate plugin' );
			}
		}

		 $res->display_with_response( false );
	}

	/**
	 * The get non skippable plugins is generated by appsbd
	 *
	 * @return array|string[]
	 */
	public function get_non_skippable_plugins() {
		/**
		 * Its for check is there any change before process
		 *
		 * @since 3.2.4
		 */
		$appsbd_plugins = vitepos_apply_filters( 'appsbd/plugins', array() );
		$non_skipable   = array(
			'woocommerce/woocommerce.php',
			'vitepos/vitepos.php',
			'vitepos-lite/vitepos-lite.php',
			'vite-coupon/vite-coupon.php',
			'vite-coupon-pro/vite-coupon-pro.php',
			'vite-rewards/vite-rewards.php',
			'vite-rewards-pro/vite-rewards-pro.php',
		);

		return array_merge( $non_skipable, $appsbd_plugins );
	}

	/**
	 * The data is generated by appsbd
	 */
	public function data() {
		$respons = new Ajax_Response();
		/**
		 * Its for check is there any change before process
		 *
		 * @since 3.2.4
		 */
		$active_plugins         = vitepos_apply_filters( 'active_plugins', get_option( 'active_plugins' ) );
		$network_active_plugins = array();
		if ( is_multisite() ) {
			$network_active_plugins = array_keys( get_site_option( 'active_sitewide_plugins' ) );
		}
		$plugin          = new \stdClass();
		$active_plugins  = array_merge( $active_plugins, $network_active_plugins );
		$plugin->plugins = array();
		$pre_skipped     = array(
			'wp-asset-clean-up-pro/wpacu.php',
			'wp-cafe/wpcafe.php',
			'wpcafe-pro/wpcafe-pro.php',
			'insert-headers-and-footers/ihaf.php',
			'wpcode-premium/wpcode.php',
			'elementor/elementor.php',
			'ewww-image-optimizer/ewww-image-optimizer.php',
			'litespeed-cache/litespeed-cache.php',
			'query-monitor/query-monitor.php',
			'loco-translate/loco.php',
			'loco-automatic-translate-addon-pro/loco-automatic-translate-addon-pro.php',
			'hide-my-wp/index.php',
			'woosuite-tax-exemption/woosuite-tax-exemption.php',
			'booked/booked.php',
			'yaypricing/yaypricing.php',
		);
		$mu_skipped      = get_option( '_vt_mu_skipped', array() );
		$non_skipable    = $this->get_non_skippable_plugins();
		foreach ( $active_plugins as $active_plugin ) {
			if ( in_array( $active_plugin, $non_skipable ) ) {
				continue;
			}
			$plugin_data = get_plugin_data( WP_PLUGIN_DIR . '/' . $active_plugin, false, false );
			if ( ! empty( $plugin_data['AuthorName'] ) && 'appsbd' == $plugin_data['AuthorName'] ) {
				continue;
			}
			$plugin_response_data          = new \stdClass();
			$plugin_response_data->name    = ! empty( $plugin_data['Name'] ) ? $plugin_data['Name'] : dirname( $active_plugin );
			$plugin_response_data->plugin  = $active_plugin;
			$plugin_response_data->version = $plugin_data['Version'];
			$plugin_response_data->author  = $plugin_data['AuthorName'];
			if ( in_array( $active_plugin, $pre_skipped ) ) {
				continue;
			} else {
				$plugin_response_data->pre_skipped = 'N';
				$plugin_response_data->is_skipped  = in_array( $active_plugin, $mu_skipped ) ? 'Y' : 'N';
			}

			$plugin->plugins[] = $plugin_response_data;

		}
		$respons->display_with_response( true, $plugin );
	}

	/**
	 * The on active is generated by appsbd
	 */
	public function on_active() {
		$this->deactivate_mu_plugin();
		$this->active_mu_plugin();
	}

	/**
	 * The on deactivate is generated by appsbd.
	 */
	public function on_deactivate() {
		$this->deactivate_mu_plugin();
	}

	/**
	 * The active mu plugin is generated by appsbd.
	 */
	public function active_mu_plugin() {
		$mu_dir = WP_CONTENT_DIR . '/mu-plugins';
		if ( ! function_exists( 'WP_Filesystem' ) ) {
			require_once ABSPATH . 'wp-admin/includes/file.php';
		}
		WP_Filesystem();
		global $wp_filesystem;

		if ( ! $wp_filesystem->is_dir( $mu_dir ) ) {
			$wp_filesystem->mkdir( $mu_dir );
		}

		$destination = $mu_dir . '/vitepos-mu.php';

		if ( ! $wp_filesystem->exists( $destination ) ) {
			$wp_filesystem->put_contents( $destination, "<?php \n" . $this->mu_content(), FS_CHMOD_FILE );
		}
	}

	/**
	 * The mu content is generated by appsbd
	 *
	 * @return string
	 */
	public function mu_content() {
		ob_start();
		?>
		/##
		# Plugin Name: Vitepos Helper
		# Description: This improves Vitepos response speed. Do not uninstall or remove it.
		# Plugin URI: http://vitepos.com
		# Version: 1.0.0
		# Author: Appsbd
		#/
		$mu_file = WP_PLUGIN_DIR . '/vitepos/vitepos/mu-helper/mu-loader.php';
		if ( file_exists( $mu_file ) ) {
			require_once $mu_file;
		}
		<?php
		$mu_data = ob_get_clean();
		return str_replace( '#', '*', $mu_data );
	}

	/**
	 * The deactivate mu plugin is generated by appsbd.
	 */
	public function deactivate_mu_plugin() {
		$mu_dir         = WP_CONTENT_DIR . '/mu-plugins';
		$mu_plugin_file = $mu_dir . '/vitepos-mu.php';
		if ( file_exists( $mu_plugin_file ) ) {
			if ( ! function_exists( 'WP_Filesystem' ) ) {
				require_once ABSPATH . 'wp-admin/includes/file.php';
			}
			WP_Filesystem();
			global $wp_filesystem;
			if ( $wp_filesystem->exists( $mu_plugin_file ) ) {
				if ( $wp_filesystem->is_writable( $mu_dir ) ) {
					$wp_filesystem->delete( $mu_plugin_file );
				}
			}
		}
	}
}
