<?php
/**
 * Its api for product
 *
 * @since: 12/07/2021
 * @author: Sarwar Hasan
 * @version 1.0.0
 * @package VitePos_Lite\Api\V1
 */

namespace VitePos_Lite\Api\V1;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

use Appsbd_Lite\V5\libs\API_Data_Response;
use Appsbd_Lite\V5\libs\AppInput;
use VitePos_Lite\Libs\API_Base;
use VitePos_Lite\Libs\POS_Product;
use VitePos_Lite\Modules\POS_Settings;

/**
 * Class pos_product_api
 *
 * @package VitePos_Lite\Api\V1
 */
class Pos_Product_Api extends API_Base {

	/**
	 * The set api base is generated by appsbd
	 *
	 * @return mixed|string
	 */
	public function set_api_base() {
		return 'product';
	}

	/**
	 * The routes is generated by appsbd
	 *
	 * @return mixed|void
	 */
	public function routes() {
		$this->register_rest_route( 'POST', 'list', array( $this, 'product_list' ) );
		$this->register_rest_route( 'POST', 'scan-product', array( $this, 'scan_product' ) );
		$this->register_rest_route( 'POST', 'list-variation', array( $this, 'product_with_variation_list' ) );
		$this->register_rest_route( 'GET', 'categories', array( $this, 'categories' ) );
		$this->register_rest_route( 'GET', 'all-categories', array( $this, 'all_categories' ) );
		$this->register_rest_route( 'GET', 'all-taxes', array( $this, 'all_taxes' ) );
		$this->register_rest_route( 'GET', 'attributes', array( $this, 'attributes' ) );
		$this->register_rest_route( 'GET', 'getStock/(?P<id>\d+)', array( $this, 'getStock' ) );
		$this->register_rest_route( 'GET', 'details/(?P<id>\d+)', array( $this, 'product_details' ) );

		$this->register_rest_route( 'POST', 'get-all-categories', array( $this, 'get_all_categories' ) );
		$this->register_rest_route( 'POST', 'add-category', array( $this, 'add_category' ) );
		$this->register_rest_route( 'POST', 'update-category', array( $this, 'update_category' ) );
		$this->register_rest_route( 'POST', 'delete-category', array( $this, 'delete_category' ) );
		$this->register_rest_route( 'POST', 'get-category', array( $this, 'get_category' ) );
		$this->register_rest_route( 'POST', 'get-attributes', array( $this, 'get_all_attributes' ) );
		$this->register_rest_route( 'POST', 'add-attribute', array( $this, 'add_attribute' ) );
		$this->register_rest_route( 'POST', 'get-attribute', array( $this, 'get_attribute' ) );
		$this->register_rest_route( 'POST', 'update-attribute', array( $this, 'update_attribute' ) );
		$this->register_rest_route( 'POST', 'delete-attribute', array( $this, 'delete_attribute' ) );
	}

	/**
	 * The set route permission is generated by appsbd
	 *
	 * @param \VitePos_Lite\Libs\any $route Its string.
	 *
	 * @return bool
	 */
	public function set_route_permission( $route ) {
		switch ( $route ) {
			case 'add-category':
				return current_user_can( 'category-add' );
			case 'update-category':
				return current_user_can( 'category-edit' );
			case 'delete-category':
				return current_user_can( 'category-delete' );

			case 'add-attribute':
				return current_user_can( 'attribute-add' );
			case 'update-attribute':
				return current_user_can( 'attribute-edit' );
			case 'delete-attribute':
				return current_user_can( 'attribute-delete' );
			default:
				return POS_Settings::is_pos_user();
		}
		return parent::set_route_permission( $route );
	}

	/**
	 * The query search filter is generated by appsbd
	 *
	 * @param \VitePos_Lite\Libs\any $where Its string.
	 * @param \VitePos_Lite\Libs\any $wp_query Its string.
	 *
	 * @return mixed|string|\VitePos_Lite\Libs\any
	 */
	public function query_search_filter( $where, $wp_query ) {
		$api_src = $wp_query->get( 'api_src' );
		if ( ! empty( $api_src ) ) {
			foreach ( $api_src as $src_item ) {
				if ( ! empty( $src_item ) ) {
					$where .= $src_item;
				}
			}
		}
		return $where;
	}
	/**
	 * The product list is generated by appsbd
	 *
	 * @return \Appsbd_Lite\V5\libs\API_Response
	 */
	public function scan_product() {
		self::set_vite_pos_request();
		$barcode   = $this->get_payload( 'barcode', '' );
		$cart_item = vitepos_get_product_by_barcode( $barcode );
		$this->response->set_response( ! empty( $cart_item ), '', $cart_item );
		return $this->response;
	}
	/**
	 * The product list is generated by appsbd
	 *
	 * @return \Appsbd_Lite\V5\libs\API_Response
	 */
	public function product_list() {
		self::set_vite_pos_request();
		$page                 = intval( $this->get_payload( 'page', 1 ) );
		$limit                = intval( $this->get_payload( 'limit', 20 ) );
		$src_props            = $this->get_payload( 'src_by', array() );
		$sort_by_props        = $this->get_payload( 'sort_by', array() );
		$response_product     = POS_Product::get_product_from_woo_products( $page, $limit, $src_props, $sort_by_props );
		$response_data        = new API_Data_Response();
		$response_data->page  = $page;
		$response_data->limit = $limit;

		if ( $response_data->set_total_records( $response_product->records ) ) {
			$response_data->rowdata = $response_product->products;
		}
		$this->response->set_response( true, '', $response_data );

		return $this->response;
	}

	/**
	 * The product list is generated by appsbd
	 *
	 * @return \Appsbd_Lite\V5\libs\API_Response
	 */
	public function product_with_variation_list() {
		self::set_vite_pos_request();
		$page                 = $this->get_payload( 'page', 1 );
		$limit                = $this->get_payload( 'limit', 20 );
		$src_props            = $this->get_payload( 'src_by', array() );
		$sort_by_props        = $this->get_payload( 'sort_by', array() );
		$response_product     = POS_Product::get_product_from_woo_products_with_variations(
			$page,
			$limit,
			$src_props,
			$sort_by_props
		);
		$response_data        = new API_Data_Response();
		$response_data->page  = $page;
		$response_data->limit = $limit;

		if ( $response_data->set_total_records( $response_product->records ) ) {
			$response_data->rowdata = $response_product->products;
		}
		$this->response->set_response( true, '', $response_data );

		return $this->response;
	}

	/**
	 * The categories is generated by appsbd
	 *
	 * @return \Appsbd_Lite\V5\libs\API_Response
	 */
	public function categories() {
		$response_product = POS_Product::get_categories();
		$this->response->set_response( true, '', $response_product );

		return $this->response;
	}
	/**
	 * The categories is generated by appsbd
	 *
	 * @return \Appsbd\V1\libs\API_Response
	 */
	public function all_categories() {
		$response_product = POS_Product::get_categories( true );
		$this->response->set_response( true, '', $response_product );

		return $this->response;
	}
	/**
	 * The categories is generated by appsbd
	 *
	 * @return \Appsbd\V1\libs\API_Response
	 */
	public function all_taxes() {
		$this->response->set_response( true, '', array() );
		return $this->response;
	}

	/**
	 * The attributes is generated by appsbd
	 *
	 * @return \Appsbd_Lite\V5\libs\API_Response
	 */
	public function attributes() {
		$response_product = array();
		$attrs_product    = wc_get_attribute_taxonomies();
		foreach ( $attrs_product as $attr ) {
			$attr_item          = new \stdClass();
			$attr_item->id      = $attr->attribute_id;
			$attr_item->name    = $attr->attribute_label;
			$attr_item->slug    = wc_attribute_taxonomy_name( $attr->attribute_name );
			$attr_item->visible = ! empty( $attr->attribute_public );
			$attr_item->options = array();
			$terms              = get_terms(
				array(
					'taxonomy'   => $attr_item->slug,
					'hide_empty' => false,
				)
			);
			foreach ( $terms as $term ) {
				$term_item            = new \stdClass();
				$term_item->id        = $term->term_id;
				$term_item->name      = $term->name;
				$term_item->slug      = $term->slug;
				$attr_item->options[] = $term_item;
			}
			$response_product[] = $attr_item;
		}
		$this->response->set_response( true, '', $response_product );

		return $this->response;
	}

	/**
	 * The getProductStockById is generated by appsbd
	 *
	 * @param any $id Its integer.
	 *
	 * @return \stdClass|null
	 */
	private function get_product_stock_by_id( $id ) {
		$product = wc_get_product( $id );
		if ( ! empty( $product ) ) {
			$product_obj                   = new \stdClass();
			$product_obj->id               = $product->get_id();
			$product_obj->name             = $product->get_name();
			$product_obj->stock_quantity   = $product->get_stock_quantity();
			$product_obj->low_stock_amount = $product->get_low_stock_amount();
			$product_obj->manage_stock     = $product->get_manage_stock();

			return $product_obj;
		}

		return null;
	}

	/**
	 * The setAttributes is generated by appsbd
	 *
	 * @param any $args Its string.
	 * @param any $type Its string.
	 *
	 * @return array
	 */
	public function get_attributes( $args, $type ) {
		$pos        = 0;
		$attributes = array();
		foreach ( $args as $attr ) {
			$attribute_object = new \WC_Product_Attribute();
			$opt_arr          = array();
			$attr['id']       = ! empty( $attr['id'] ) ? absint( $attr['id'] ) : $attr['id'];
			if ( ! empty( $attr['id'] ) ) {
				$attribute_object->set_id( wc_attribute_taxonomy_id_by_name( $attr['slug'] ) );
				$attribute_object->set_name( $attr['slug'] );
			} else {
				$attribute_object->set_name( $attr['name'] );

			}
			foreach ( $attr['options'] as $option ) {
				$opt_arr[] = $option['name'];
			}
			if ( 'variable' == $type ) {
				$attribute_object->set_variation( true );
			}
			$attribute_object->set_position( $pos++ );
			$attribute_object->set_options( $opt_arr );
			$attribute_object->set_visible( $attr['visible'] );
			array_push( $attributes, $attribute_object );
		}
		return $attributes;
	}

	/**
	 * The getStock is generated by appsbd
	 *
	 * @param any $data Its string.
	 *
	 * @return \Appsbd_Lite\V5\libs\API_Response
	 */
	public function get_stock( $data ) {
		if ( ! empty( $data['id'] ) ) {
			$id          = intval( $data['id'] );
			$product_obj = $this->get_product_stock_by_id( $id );
			$this->set_response( true, 'data found', $product_obj );

			return $this->response;
		}
		$this->set_response( false, 'data not found or invalid param' );

		return $this->response;
	}

	/**
	 * The delete product is generated by appsbd
	 *
	 *  @return \Appsbd_Lite\V5\libs\API_Response
	 */
	public function delete_product() {
		if ( ! empty( $this->payload ) ) {
			$id      = intval( $this->payload['id'] );
			$product = wc_get_product( $id );
			if ( ! empty( $product ) ) {
				if ( $product->is_type( 'variable' ) ) {
					foreach ( $product->get_children() as $child_id ) {
						$this->delete_variationProduct( $child_id );
					}
				}
				if ( $product->delete() ) {
					$this->add_info( 'Successfully deleted' );
					$this->response->set_response( true, '' );
					return $this->response;
				} else {
					$this->add_error( 'Delete failed' );
					$this->response->set_response( false, '' );
					return $this->response;
				}
			} else {
				$this->add_error( 'Delete failed' );
				$this->response->set_response( false, '' );
				return $this->response;
			}
		} else {
			$this->add_error( 'Invalid request' );
			$this->response->set_response( false, '' );
			return $this->response;
		}
	}

	/**
	 * The delete variationProduct is generated by appsbd
	 *
	 * @param any $child_id Its child id param.
	 *
	 * @return mixed
	 */
	public function delete_variationProduct( $child_id ) {
		$child = wc_get_product( $child_id );
		if ( $child ) {
			$child->delete();
			return $child;
		} else {
			$this->add_error( 'invalid requiest' );
		}
	}


	/**
	 * The getProductById is generated by appsbd
	 *
	 * @param any $id Its integer.
	 *
	 * @return POS_Product
	 */
	public function get_product_by_id( $id ) {
		$product     = wc_get_product( $id );
		$pos_product = POS_Product::get_product_data( $product, true );
		return $pos_product;
	}

	/**
	 * The product details is generated by appsbd
	 *
	 * @param any $data Its string.
	 *
	 * @return \Appsbd_Lite\V5\libs\API_Response
	 */
	public function product_details( $data ) {
		if ( ! empty( $data['id'] ) ) {
			$id          = intval( $data['id'] );
			$product_obj = $this->get_product_by_id( $id );
			$this->set_response( true, 'data found', $product_obj );

			return $this->response;
		}
		$this->set_response( false, 'Data not found or invalid param' );

		return $this->response;
	}

	/**
	 * The get all categories is generated by appsbd
	 *
	 * @return \Appsbd\V1\libs\API_Response
	 */
	public function get_all_categories() {
		$page          = intval( $this->get_payload( 'page', 1 ) );
		$limit         = intval( $this->get_payload( 'limit', 10 ) );
		$response_data = new API_Data_Response();
		$src_props     = $this->get_payload( 'src_by', array() );
		$sort_props    = $this->get_payload( 'sort_by', array() );
		$orderby       = 'name';
		$order         = 'asc';

		if ( ! empty( $sort_props['prop'] ) ) {
			$orderby = $sort_props['prop'];
		}
		if ( ! empty( $sort_props['order'] ) ) {
			$order = $sort_props['order'];
		}

		$search = '';
		foreach ( $src_props as $prop ) {
			if (
				( 'name' === $prop['prop'] || '*' === $prop['prop'] ) &&
				! empty( $prop['val'] )
			) {
				$search = sanitize_text_field( $prop['val'] );
			}
		}

		$offset = ( $page - 1 ) * $limit;

		$cat_args = array(
			'taxonomy'   => 'product_cat',
			'orderby'    => $orderby,
			'order'      => $order,
			'hide_empty' => false,
			'number'     => $limit,
			'offset'     => $offset,
		);

		if ( ! empty( $search ) ) {
			$cat_args['search'] = $search;
		}
		$response_categories = get_terms( $cat_args );
		if ( ! is_wp_error( $response_categories ) && ! empty( $response_categories ) ) {
			foreach ( $response_categories as $category ) {
				$id           = $category->term_id;
				$thumbnail_id = get_term_meta( $id, 'thumbnail_id', true );
				if ( $thumbnail_id ) {
					$category->image = wp_get_attachment_image_url( $thumbnail_id );
				}
			}
		}

		$count_args = $cat_args;
		unset( $count_args['number'], $count_args['offset'] );
		$total_category       = count( get_terms( $count_args ) );
		$response_data->page  = intval( $page );
		$response_data->limit = intval( $limit );
		if ( $response_data->set_total_records( $total_category ) ) {
			$response_data->rowdata = array_values( (array) $response_categories );
		}
		$this->response->set_response( true, '', $response_data );

		return $this->response;
	}
	/**
	 * The add category is generated by appsbd
	 *
	 * @return \Appsbd\V1\libs\API_Response
	 */
	public function add_category() {
		if ( ! empty( $this->payload ) ) {
			$name = $this->get_payload( 'category_name' );
			if ( empty( $name ) ) {
				$this->add_error( 'Category name is required' );
				$this->response->set_response( false, '' );

				return $this->response->get_response();
			}
			$parent_id   = $this->get_payload( 'category_parent' );
			$description = $this->get_payload( 'category_description' );

			$existing_term = get_terms(
				array(
					'taxonomy'   => 'product_cat',
					'name'       => $name,
					'hide_empty' => false,
					'parent'     => $parent_id,
				)
			);

			if ( ! empty( $existing_term ) && ! is_wp_error( $existing_term ) ) {
				$this->add_error( 'A category with the same name already exists with the selected parent.' );
				$this->response->set_response( false, '' );
				return $this->response->get_response();
			}

			$term = wp_insert_term(
				$name,
				'product_cat',
				array(
					'description' => $description,
					'parent'      => $parent_id,
				)
			);
			if ( is_wp_error( $term ) ) {
				$this->add_error( $term->get_error_message() );
				$this->response->set_response( false, '' );

				return $this->response->get_response();
			}
			$term_id = $term['term_id'];

			if ( ! empty( $term_id ) ) {
				$this->call_category_action( $term_id );
			}

			$this->add_info( 'Category created successfully' );
			$this->response->set_response( true, '' );

			return $this->response->get_response();
		}
		$this->add_error( 'Failed to add' );
		$this->response->set_response( false, '' );

		return $this->response->get_response();
	}

	/**
	 * The update category is generated by appsbd
	 *
	 * @return \Appsbd\V1\libs\API_Response
	 */
	public function update_category() {
		if ( ! empty( $this->payload ) ) {
			$cat_id = $this->get_payload( 'id' );
			if ( empty( $cat_id ) ) {
				$this->add_error( 'Invalid id' );
				$this->response->set_response( false, '' );

				return $this->response->get_response();
			}
			$name = $this->get_payload( 'category_name' );
			if ( empty( $name ) ) {
				$this->add_error( 'Category name is required' );
				$this->response->set_response( false, '' );

				return $this->response->get_response();
			}
			$parent_id   = $this->get_payload( 'category_parent' );
			$description = $this->get_payload( 'category_description' );

			$existing_term = get_terms(
				array(
					'taxonomy'   => 'product_cat',
					'name'       => $name,
					'hide_empty' => false,
					'parent'     => $parent_id,
					'exclude'    => array( $cat_id ),
				)
			);

			if ( ! empty( $existing_term ) && ! is_wp_error( $existing_term ) ) {
				$this->add_error( 'A category with the same name already exists with the selected parent.' );
				$this->response->set_response( false, '' );
				return $this->response->get_response();
			}

			$slug        = sanitize_title( $name );
			$parent_term = get_term( $parent_id, 'product_cat' );

			if ( $parent_id && ! empty( $parent_term->slug ) ) {
				$slug .= '-' . $parent_term->slug;
			}

			$updated_term = wp_update_term(
				$cat_id,
				'product_cat',
				array(
					'name'        => $name,
					'slug'        => $slug,
					'description' => $description,
					'parent'      => $parent_id,
				)
			);
			if ( is_wp_error( $updated_term ) ) {
				$this->add_error( $updated_term->get_error_message() );
				$this->response->set_response( false, '' );

				return $this->response->get_response();
			}
			$term_id = $updated_term['term_id'];

			if ( ! empty( $term_id ) ) {
				$this->call_category_action( $term_id );
			}
			$this->add_info( 'Category updated successfully' );
			$this->response->set_response( true, '' );

			return $this->response->get_response();
		}
		$this->add_error( 'Failed to update' );
		$this->response->set_response( false, '' );

		return $this->response->get_response();
	}

	/**
	 * The delete category is generated by appsbd
	 *
	 * @return \Appsbd\V1\libs\API_Response
	 */
	public function delete_category() {
		$id = $this->get_payload( 'id' );
		if ( ! empty( $id ) ) {
			$deleted_category = wp_delete_term( $id, 'product_cat' );
			if ( is_wp_error( $deleted_category ) ) {
				$this->add_error( $deleted_category->get_error_message() );
				$this->response->set_response( false, '' );

				return $this->response->get_response();
			}
			$this->add_info( 'Category deleted successfully' );
			$this->response->set_response( true, '' );

			return $this->response;
		}

		$this->add_error( 'Failed to delete' );
		$this->response->set_response( false, '' );

		return $this->response->get_response();
	}


	/**
	 * The get category is generated by appsbd
	 *
	 * @return \Appsbd\V1\libs\API_Response
	 */
	public function get_category() {
		$category_id = $this->get_payload( 'id' );
		if ( ! empty( $category_id ) ) {
			$category = get_term( $category_id, 'product_cat' );
			if ( ! empty( $category ) ) {
				$term_id      = $category->term_id;
				$thumbnail_id = get_term_meta( $term_id, 'thumbnail_id', true );
				$image_url    = $thumbnail_id ? wp_get_attachment_url( $thumbnail_id ) : '';
				$res_data     = array(
					'category_name'        => $category->name,
					'category_parent'      => $category->parent,
					'category_description' => $category->description,
					'image'                => $image_url,
				);
				$this->response->set_response( true, '', $res_data );

				return $this->response;
			}
			$this->response->set_response( false, 'No category found' );

			return $this->response;
		}
		$this->response->set_response( false, 'Invalid category id' );

		return $this->response;
	}

	/**
	 * The get all attributes is generated by appsbd
	 *
	 * @return \Appsbd_Lite\V5\libs\API_Response
	 */
	public function get_all_attributes() {
		$page          = $this->get_payload( 'page', 1 );
		$limit         = $this->get_payload( 'limit', 10 );
		$response_data = new API_Data_Response();
		$src_props     = $this->get_payload( 'src_by', array() );
		$sort_props    = $this->get_payload( 'sort_by', array() );

		$attributes = wc_get_attribute_taxonomies();
		$final_data = array();
		if ( ! empty( $attributes ) ) {
			foreach ( $attributes as $attr ) {
				$taxonomy = wc_attribute_taxonomy_name( $attr->attribute_name );
				$terms    = get_terms(
					array(
						'taxonomy'   => $taxonomy,
						'hide_empty' => false,
					)
				);

				$term_list = array();
				if ( ! is_wp_error( $terms ) && ! empty( $terms ) ) {
					foreach ( $terms as $term ) {
						$term_list[] = array(
							'id'          => $term->term_id,
							'name'        => $term->name,
							'slug'        => $term->slug,
							'description' => $term->description,
						);
					}
				}
				$final_data[] = array(
					'id'    => $attr->attribute_id,
					'name'  => $attr->attribute_label,
					'slug'  => $attr->attribute_name,
					'terms' => $term_list,
				);
			}
		}

		if ( ! empty( $src_props ) ) {
			foreach ( $src_props as $src ) {
				$prop = $src['prop'] ?? '';
				$val  = $src['val'] ?? '';
				$opr  = strtolower( $src['opr'] ?? 'like' );

				$final_data = array_filter(
					$final_data,
					function ( $item ) use ( $prop, $val, $opr ) {
						if ( '*' === $prop ) {
							foreach ( array( 'name', 'slug', 'id' ) as $field ) {
								if ( isset( $item[ $field ] ) && stripos( $item[ $field ], $val ) !== false ) {
									return true;
								}
							}

							return false;
						}

						if ( isset( $item[ $prop ] ) ) {
							switch ( $opr ) {
								case '=':
									return $item[ $prop ] == $val;
								case 'like':
									return stripos( $item[ $prop ], $val ) !== false;
								default:
									return true;
							}
						}

						return false;
					}
				);
			}
		}

		$total_records = count( $final_data );
		$offset        = ( $page - 1 ) * $limit;
		$paginated     = array_slice( $final_data, $offset, $limit );

		$response_data->page  = $page;
		$response_data->limit = $limit;
		if ( $response_data->set_total_records( $total_records ) ) {
			$response_data->rowdata = array_values( (array) $paginated );
		}
		$this->response->set_response( true, '', $response_data );

		return $this->response;
	}

	/**
	 * The add attributes is generated by appsbd
	 *
	 * @return \Appsbd\V1\libs\API_Response
	 */
	public function add_attribute() {
		if ( ! empty( $this->payload ) ) {
			$attr_label = $this->get_payload( 'name' );

			if ( ! empty( $attr_label ) ) {
				$attr_slug = wc_sanitize_taxonomy_name( $attr_label );
				$taxonomy  = 'pa_' . $attr_slug;

				$exists              = false;
				$existing_attributes = wc_get_attribute_taxonomies();

				foreach ( $existing_attributes as $attribute ) {
					if ( $attribute->attribute_name === $attr_slug ) {
						$exists = true;
					}
				}
				if ( ! $exists ) {
					$attribute_id = wc_create_attribute(
						array(
							'name' => $attr_label,
						)
					);

					if ( is_wp_error( $attribute_id ) ) {
						$this->add_error( $attribute_id->get_error_message() );
						$this->response->set_response( false, '' );

						return $this->response->get_response();
					}

					register_taxonomy(
						$taxonomy,
						array( 'product' ),
						array(
							'hierarchical' => true,
							'labels'       => array(
								'name' => $attr_label,
							),
							'show_ui'      => false,
							'query_var'    => true,
							'rewrite'      => false,
							'public'       => false,
						)
					);

					$terms = $this->get_payload( 'terms' );
					if ( ! empty( $terms ) ) {
						foreach ( $terms as $term ) {
							$term_name = sanitize_text_field( $term['name'] );
							$term_desc = isset( $term['description'] ) ? sanitize_text_field( $term['description'] ) : '';
							if ( ! term_exists( $term_name, $taxonomy ) ) {
								wp_insert_term(
									$term_name,
									$taxonomy,
									array(
										'description' => $term_desc,
									)
								);
							}
						}
					}
					$this->add_info( 'Attribute created successfully ' );
					$this->response->set_response( true, '' );

					return $this->response->get_response();
				}
				$this->add_error( 'Name of the attribute is already exist' );
				$this->response->set_response( false, '' );

				return $this->response->get_response();
			}
			$this->add_error( 'Attribute name is missing' );
			$this->response->set_response( false, '' );

			return $this->response->get_response();
		}
		$this->response->set_response( false, 'Failed to add' );

		return $this->response;
	}

	/**
	 * The get attribute is generated by appsbd
	 *
	 * @return \Appsbd\V1\libs\API_Response
	 */
	public function get_attribute() {
		$attribute_id = $this->get_payload( 'id' );
		if ( ! empty( $attribute_id ) ) {
			$attributes = wc_get_attribute_taxonomies();
			$attribute  = null;
			foreach ( $attributes as $attr ) {
				if ( intval( $attr->attribute_id ) === intval( $attribute_id ) ) {
					$attribute = $attr;
					break;
				}
			}
			if ( ! empty( $attribute ) ) {
				$attribute_slug = $attribute->attribute_name;
				$taxonomy       = 'pa_' . $attribute_slug;
				$terms          = get_terms(
					array(
						'taxonomy'   => $taxonomy,
						'hide_empty' => false,
					)
				);

				$terms_data = array();
				if ( ! is_wp_error( $terms ) && ! empty( $terms ) ) {
					foreach ( $terms as $term ) {
						$terms_data[] = array(
							'term_id'     => $term->term_id,
							'name'        => $term->name,
							'description' => $term->description,
						);
					}
				}
				$attribute_data = array(
					'id'    => $attribute->attribute_id,
					'name'  => $attribute->attribute_name,
					'terms' => $terms_data,
				);
				$this->response->set_response( true, '', $attribute_data );

				return $this->response;
			}
			$this->add_error( 'No attribute found with this id' );
			$this->response->set_response( false, '' );

			return $this->response->get_response();
		}
		$this->add_error( 'Invalid id' );
		$this->response->set_response( false, '' );

		return $this->response->get_response();
	}

	/**
	 * The update attribute is generated by appsbd
	 *
	 * @return \Appsbd\V1\libs\API_Response
	 */
	public function update_attribute() {
		$attribute_id = $this->get_payload( 'id' );
		if ( ! empty( $attribute_id ) ) {
			$attr_label = $this->get_payload( 'name' );
			if ( empty( $attr_label ) ) {
				$this->add_error( 'Attribute name is missing' );
				$this->response->set_response( false, '' );

				return $this->response->get_response();
			}
			$attributes = wc_get_attribute_taxonomies();
			$attribute  = null;
			foreach ( $attributes as $attr ) {
				if ( $attr->attribute_id === $attribute_id ) {
					$attribute = $attr;
					break;
				}
			}
			if ( ! empty( $attribute ) ) {
				$updated_attribute_id = wc_create_attribute(
					array(
						'id'   => $attribute_id,
						'name' => $attr_label,
					)
				);
				if ( is_wp_error( $updated_attribute_id ) ) {
					$this->add_error( $updated_attribute_id->get_error_message() );
					$this->response->set_response( false, '' );

					return $this->response;
				}
				$terms_data = $this->get_payload( 'terms', array() );
				if ( ! empty( $terms_data ) ) {
					$taxonomy = wc_attribute_taxonomy_name( wc_sanitize_taxonomy_name( $attr_label ) );

					$existing_terms = get_terms(
						array(
							'taxonomy'   => $taxonomy,
							'hide_empty' => false,
						)
					);

					$incoming_term_ids = array();
					foreach ( $terms_data as $term ) {
						$name        = sanitize_text_field( $term['name'] ?? '' );
						$description = sanitize_text_field( $term['description'] ?? '' );

						if ( empty( $name ) ) {
							continue;
						}

						if ( ! empty( $term['term_id'] ) ) {
							wp_update_term(
								$term['term_id'],
								$taxonomy,
								array(
									'name'        => $name,
									'description' => $description,
								)
							);
							$incoming_term_ids[] = (int) $term['term_id'];
						} elseif ( ! term_exists( $name, $taxonomy ) ) {
								$new_term = wp_insert_term(
									$name,
									$taxonomy,
									array(
										'description' => $description,
									)
								);
							if ( ! is_wp_error( $new_term ) && ! empty( $new_term['term_id'] ) ) {
								$incoming_term_ids[] = (int) $new_term['term_id'];
							}
						} else {
							$existing = get_term_by( 'name', $name, $taxonomy );
							if ( $existing ) {
								$incoming_term_ids[] = (int) $existing->term_id;
							}
						}
					}

					foreach ( $existing_terms as $existing_term ) {
						if ( ! in_array( (int) $existing_term->term_id, $incoming_term_ids ) ) {
							wp_delete_term( $existing_term->term_id, $taxonomy );
						}
					}
				}
				$this->add_info( 'Attribute updated successfully' );
				$this->response->set_response( true, '' );

				return $this->response;
			}
			$this->add_error( 'Invalid attribute to update' );
			$this->response->set_response( false, '' );

			return $this->response;
		}
		$this->add_error( 'Failed to update' );
		$this->response->set_response( false, '' );

		return $this->response;
	}

	/**
	 * The delete attribute is generated by appsbd
	 *
	 * @return \Appsbd_Lite\V5\libs\API_Response
	 */
	public function delete_attribute() {
		if ( ! empty( $this->payload ) ) {
			$attribute_id = $this->get_payload( 'id' );

			if ( ! $attribute_id ) {
				$this->add_error( 'Invalid attribute id' );
				$this->response->set_response( false, '' );

				return $this->response->get_response();
			}

			$deleted = wc_delete_attribute( $attribute_id );

			if ( is_wp_error( $deleted ) ) {
				$this->add_error( $deleted->get_error_message() );
				$this->response->set_response( false, '' );

				return $this->response->get_response();
			}

			if ( ! empty( $deleted ) ) {
				$this->add_info( 'Attribute deleted successfully' );
				$this->response->set_response( true, '' );
			} else {
				$this->add_error( 'Attribute not found or could not be deleted' );
				$this->response->set_response( false, '' );
			}

			return $this->response->get_response();
		}

		$this->response->set_response( false, 'Failed to delete' );

		return $this->response;
	}

	/**
	 * The call category action is generated by appsbd
	 *
	 * @param mixed $category_id It is category_id param.
	 */
	public function call_category_action( $category_id ) {
		/**
		 * Its for product feature update
		 *
		 * @since 3.2.3
		 */
		do_action( 'apbd-vtpos/action/save-category-image', $category_id );
	}
}
